# Generated by Django 4.2.6 on 2023-11-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_my_file_material_myfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='file_name',
            new_name='filename',
        ),
    ]
