# Generated by Django 4.2.6 on 2023-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_file_name_material_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsby',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='news',
            name='newstitle',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
