# Generated by Django 4.2.6 on 2023-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_news_newsby_news_newstitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='id',
        ),
        migrations.AlterField(
            model_name='material',
            name='ids',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
