# Generated by Django 4.2.6 on 2023-11-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('username', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('fname', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=64)),
                ('regdate', models.CharField(max_length=30)),
            ],
        ),
    ]
