# Generated by Django 4.2.6 on 2023-11-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_registration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='aadhar',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
