# Generated by Django 4.2.6 on 2024-04-10 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='enno',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
