# Generated by Django 4.2.6 on 2024-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_registration_enno'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pic',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
