# Generated by Django 4.2.6 on 2024-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_registration_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='pic',
        ),
    ]
