# Generated by Django 4.2.6 on 2024-04-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_registration_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
